// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdu5rN6jGRaELF2DAfJ9LQXL4CC5a5rl0',
    appId: '1:57835002520:web:9a5118f5b63efa28f34eed',
    messagingSenderId: '57835002520',
    projectId: 'jawara-c24de',
    authDomain: 'jawara-c24de.firebaseapp.com',
    storageBucket: 'jawara-c24de.firebasestorage.app',
    measurementId: 'G-9YXDCT7P7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfrCx4I5G2Ugc8KLObiFoOocjG52R3b4M',
    appId: '1:57835002520:android:5be2fda9e050896ef34eed',
    messagingSenderId: '57835002520',
    projectId: 'jawara-c24de',
    storageBucket: 'jawara-c24de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhmjRFu_A_dtO0s1z-AxGE88tjOay5TFY',
    appId: '1:57835002520:ios:6b60fdd678cc287af34eed',
    messagingSenderId: '57835002520',
    projectId: 'jawara-c24de',
    storageBucket: 'jawara-c24de.firebasestorage.app',
    iosBundleId: 'com.example.jawara',
  );
}
